server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: greeting-service-route
          uri: grpc://localhost:6565
          predicates:
            - Path=/greetings/**
          filters:
            - name: JsonToGrpc
              args:
                protoDescriptor: classpath:descriptor_set.desc
                protoFile: classpath:greeting.proto
                service: GreetingService
                method: Hello
      httpclient:
        ssl:
          use-insecure-trust-manager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always